#!/bin/bash
#
# test while loop 2
#

go=1
while (( go ))
do
    echo "Input command(pwd, date, quit) : "
    read cmd

    case $cmd in
        pwd) pwd ;;
        date) date ;;
        quit) go=0 ;;
        *) echo "Wrong command" ;;
    esac
done
